// ISO 3166-1 alpha-2 → flag emoji + localized country name lookups.
// Comprehensive map covering all live + observers + special territories
// referenced by the dataset, plus common aliases.

export function flagEmoji(code: string | null | undefined): string {
  if (!code || code.length !== 2) return "🏳️";
  const A = 0x1f1e6;
  const a = "A".charCodeAt(0);
  const upper = code.toUpperCase();
  const cp1 = A + (upper.charCodeAt(0) - a);
  const cp2 = A + (upper.charCodeAt(1) - a);
  return String.fromCodePoint(cp1, cp2);
}

interface NameEntry {
  ko: string;
  en: string;
}

const NAMES: Record<string, NameEntry> = {
  AD: { ko: "안도라", en: "Andorra" },
  AE: { ko: "아랍에미리트", en: "United Arab Emirates" },
  AF: { ko: "아프가니스탄", en: "Afghanistan" },
  AG: { ko: "앤티가 바부다", en: "Antigua and Barbuda" },
  AI: { ko: "앵귈라", en: "Anguilla" },
  AL: { ko: "알바니아", en: "Albania" },
  AM: { ko: "아르메니아", en: "Armenia" },
  AO: { ko: "앙골라", en: "Angola" },
  AQ: { ko: "남극", en: "Antarctica" },
  AR: { ko: "아르헨티나", en: "Argentina" },
  AS: { ko: "아메리칸사모아", en: "American Samoa" },
  AT: { ko: "오스트리아", en: "Austria" },
  AU: { ko: "호주", en: "Australia" },
  AW: { ko: "아루바", en: "Aruba" },
  AX: { ko: "올란드 제도", en: "Åland Islands" },
  AZ: { ko: "아제르바이잔", en: "Azerbaijan" },
  BA: { ko: "보스니아 헤르체고비나", en: "Bosnia and Herzegovina" },
  BB: { ko: "바베이도스", en: "Barbados" },
  BD: { ko: "방글라데시", en: "Bangladesh" },
  BE: { ko: "벨기에", en: "Belgium" },
  BF: { ko: "부르키나파소", en: "Burkina Faso" },
  BG: { ko: "불가리아", en: "Bulgaria" },
  BH: { ko: "바레인", en: "Bahrain" },
  BI: { ko: "부룬디", en: "Burundi" },
  BJ: { ko: "베냉", en: "Benin" },
  BL: { ko: "생바르텔레미", en: "Saint Barthélemy" },
  BM: { ko: "버뮤다", en: "Bermuda" },
  BN: { ko: "브루나이", en: "Brunei" },
  BO: { ko: "볼리비아", en: "Bolivia" },
  BQ: { ko: "보네르", en: "Bonaire, Sint Eustatius and Saba" },
  BR: { ko: "브라질", en: "Brazil" },
  BS: { ko: "바하마", en: "Bahamas" },
  BT: { ko: "부탄", en: "Bhutan" },
  BV: { ko: "부베섬", en: "Bouvet Island" },
  BW: { ko: "보츠와나", en: "Botswana" },
  BY: { ko: "벨라루스", en: "Belarus" },
  BZ: { ko: "벨리즈", en: "Belize" },
  CA: { ko: "캐나다", en: "Canada" },
  CC: { ko: "코코스 제도", en: "Cocos (Keeling) Islands" },
  CD: { ko: "콩고민주공화국", en: "DR Congo" },
  CF: { ko: "중앙아프리카공화국", en: "Central African Republic" },
  CG: { ko: "콩고", en: "Congo" },
  CH: { ko: "스위스", en: "Switzerland" },
  CI: { ko: "코트디부아르", en: "Côte d'Ivoire" },
  CK: { ko: "쿡 제도", en: "Cook Islands" },
  CL: { ko: "칠레", en: "Chile" },
  CM: { ko: "카메룬", en: "Cameroon" },
  CN: { ko: "중국", en: "China" },
  CO: { ko: "콜롬비아", en: "Colombia" },
  CR: { ko: "코스타리카", en: "Costa Rica" },
  CU: { ko: "쿠바", en: "Cuba" },
  CV: { ko: "카보베르데", en: "Cape Verde" },
  CW: { ko: "퀴라소", en: "Curaçao" },
  CX: { ko: "크리스마스섬", en: "Christmas Island" },
  CY: { ko: "키프로스", en: "Cyprus" },
  CZ: { ko: "체코", en: "Czechia" },
  DE: { ko: "독일", en: "Germany" },
  DJ: { ko: "지부티", en: "Djibouti" },
  DK: { ko: "덴마크", en: "Denmark" },
  DM: { ko: "도미니카", en: "Dominica" },
  DO: { ko: "도미니카공화국", en: "Dominican Republic" },
  DZ: { ko: "알제리", en: "Algeria" },
  EC: { ko: "에콰도르", en: "Ecuador" },
  EE: { ko: "에스토니아", en: "Estonia" },
  EG: { ko: "이집트", en: "Egypt" },
  EH: { ko: "서사하라", en: "Western Sahara" },
  ER: { ko: "에리트레아", en: "Eritrea" },
  ES: { ko: "스페인", en: "Spain" },
  ET: { ko: "에티오피아", en: "Ethiopia" },
  FI: { ko: "핀란드", en: "Finland" },
  FJ: { ko: "피지", en: "Fiji" },
  FK: { ko: "포클랜드 제도", en: "Falkland Islands" },
  FM: { ko: "미크로네시아", en: "Micronesia" },
  FO: { ko: "페로 제도", en: "Faroe Islands" },
  FR: { ko: "프랑스", en: "France" },
  GA: { ko: "가봉", en: "Gabon" },
  GB: { ko: "영국", en: "United Kingdom" },
  GD: { ko: "그레나다", en: "Grenada" },
  GE: { ko: "조지아", en: "Georgia" },
  GF: { ko: "프랑스령 기아나", en: "French Guiana" },
  GG: { ko: "건지", en: "Guernsey" },
  GH: { ko: "가나", en: "Ghana" },
  GI: { ko: "지브롤터", en: "Gibraltar" },
  GL: { ko: "그린란드", en: "Greenland" },
  GM: { ko: "감비아", en: "Gambia" },
  GN: { ko: "기니", en: "Guinea" },
  GP: { ko: "과들루프", en: "Guadeloupe" },
  GQ: { ko: "적도 기니", en: "Equatorial Guinea" },
  GR: { ko: "그리스", en: "Greece" },
  GS: { ko: "사우스조지아 사우스샌드위치 제도", en: "South Georgia and the South Sandwich Islands" },
  GT: { ko: "과테말라", en: "Guatemala" },
  GU: { ko: "괌", en: "Guam" },
  GW: { ko: "기니비사우", en: "Guinea-Bissau" },
  GY: { ko: "가이아나", en: "Guyana" },
  HK: { ko: "홍콩", en: "Hong Kong" },
  HM: { ko: "허드 맥도널드 제도", en: "Heard Island and McDonald Islands" },
  HN: { ko: "온두라스", en: "Honduras" },
  HR: { ko: "크로아티아", en: "Croatia" },
  HT: { ko: "아이티", en: "Haiti" },
  HU: { ko: "헝가리", en: "Hungary" },
  ID: { ko: "인도네시아", en: "Indonesia" },
  IE: { ko: "아일랜드", en: "Ireland" },
  IL: { ko: "이스라엘", en: "Israel" },
  IM: { ko: "맨섬", en: "Isle of Man" },
  IN: { ko: "인도", en: "India" },
  IO: { ko: "영국령 인도양 지역", en: "British Indian Ocean Territory" },
  IQ: { ko: "이라크", en: "Iraq" },
  IR: { ko: "이란", en: "Iran" },
  IS: { ko: "아이슬란드", en: "Iceland" },
  IT: { ko: "이탈리아", en: "Italy" },
  JE: { ko: "저지", en: "Jersey" },
  JM: { ko: "자메이카", en: "Jamaica" },
  JO: { ko: "요르단", en: "Jordan" },
  JP: { ko: "일본", en: "Japan" },
  KE: { ko: "케냐", en: "Kenya" },
  KG: { ko: "키르기스스탄", en: "Kyrgyzstan" },
  KH: { ko: "캄보디아", en: "Cambodia" },
  KI: { ko: "키리바시", en: "Kiribati" },
  KM: { ko: "코모로", en: "Comoros" },
  KN: { ko: "세인트키츠 네비스", en: "Saint Kitts and Nevis" },
  KP: { ko: "북한", en: "North Korea" },
  KR: { ko: "대한민국", en: "South Korea" },
  KW: { ko: "쿠웨이트", en: "Kuwait" },
  KY: { ko: "케이맨 제도", en: "Cayman Islands" },
  KZ: { ko: "카자흐스탄", en: "Kazakhstan" },
  LA: { ko: "라오스", en: "Laos" },
  LB: { ko: "레바논", en: "Lebanon" },
  LC: { ko: "세인트루시아", en: "Saint Lucia" },
  LI: { ko: "리히텐슈타인", en: "Liechtenstein" },
  LK: { ko: "스리랑카", en: "Sri Lanka" },
  LR: { ko: "라이베리아", en: "Liberia" },
  LS: { ko: "레소토", en: "Lesotho" },
  LT: { ko: "리투아니아", en: "Lithuania" },
  LU: { ko: "룩셈부르크", en: "Luxembourg" },
  LV: { ko: "라트비아", en: "Latvia" },
  LY: { ko: "리비아", en: "Libya" },
  MA: { ko: "모로코", en: "Morocco" },
  MC: { ko: "모나코", en: "Monaco" },
  MD: { ko: "몰도바", en: "Moldova" },
  ME: { ko: "몬테네그로", en: "Montenegro" },
  MF: { ko: "생마르탱", en: "Saint Martin" },
  MG: { ko: "마다가스카르", en: "Madagascar" },
  MH: { ko: "마셜 제도", en: "Marshall Islands" },
  MK: { ko: "북마케도니아", en: "North Macedonia" },
  ML: { ko: "말리", en: "Mali" },
  MM: { ko: "미얀마", en: "Myanmar" },
  MN: { ko: "몽골", en: "Mongolia" },
  MO: { ko: "마카오", en: "Macao" },
  MP: { ko: "북마리아나 제도", en: "Northern Mariana Islands" },
  MQ: { ko: "마르티니크", en: "Martinique" },
  MR: { ko: "모리타니", en: "Mauritania" },
  MS: { ko: "몬트세랫", en: "Montserrat" },
  MT: { ko: "몰타", en: "Malta" },
  MU: { ko: "모리셔스", en: "Mauritius" },
  MV: { ko: "몰디브", en: "Maldives" },
  MW: { ko: "말라위", en: "Malawi" },
  MX: { ko: "멕시코", en: "Mexico" },
  MY: { ko: "말레이시아", en: "Malaysia" },
  MZ: { ko: "모잠비크", en: "Mozambique" },
  NA: { ko: "나미비아", en: "Namibia" },
  NC: { ko: "뉴칼레도니아", en: "New Caledonia" },
  NE: { ko: "니제르", en: "Niger" },
  NF: { ko: "노퍽섬", en: "Norfolk Island" },
  NG: { ko: "나이지리아", en: "Nigeria" },
  NI: { ko: "니카라과", en: "Nicaragua" },
  NL: { ko: "네덜란드", en: "Netherlands" },
  NO: { ko: "노르웨이", en: "Norway" },
  NP: { ko: "네팔", en: "Nepal" },
  NR: { ko: "나우루", en: "Nauru" },
  NU: { ko: "니우에", en: "Niue" },
  NZ: { ko: "뉴질랜드", en: "New Zealand" },
  OM: { ko: "오만", en: "Oman" },
  PA: { ko: "파나마", en: "Panama" },
  PE: { ko: "페루", en: "Peru" },
  PF: { ko: "프랑스령 폴리네시아", en: "French Polynesia" },
  PG: { ko: "파푸아뉴기니", en: "Papua New Guinea" },
  PH: { ko: "필리핀", en: "Philippines" },
  PK: { ko: "파키스탄", en: "Pakistan" },
  PL: { ko: "폴란드", en: "Poland" },
  PM: { ko: "생피에르 미클롱", en: "Saint Pierre and Miquelon" },
  PN: { ko: "핏케언 제도", en: "Pitcairn Islands" },
  PR: { ko: "푸에르토리코", en: "Puerto Rico" },
  PS: { ko: "팔레스타인", en: "Palestine" },
  PT: { ko: "포르투갈", en: "Portugal" },
  PW: { ko: "팔라우", en: "Palau" },
  PY: { ko: "파라과이", en: "Paraguay" },
  QA: { ko: "카타르", en: "Qatar" },
  RE: { ko: "레위니옹", en: "Réunion" },
  RO: { ko: "루마니아", en: "Romania" },
  RS: { ko: "세르비아", en: "Serbia" },
  RU: { ko: "러시아", en: "Russia" },
  RW: { ko: "르완다", en: "Rwanda" },
  SA: { ko: "사우디아라비아", en: "Saudi Arabia" },
  SB: { ko: "솔로몬 제도", en: "Solomon Islands" },
  SC: { ko: "세이셸", en: "Seychelles" },
  SD: { ko: "수단", en: "Sudan" },
  SE: { ko: "스웨덴", en: "Sweden" },
  SG: { ko: "싱가포르", en: "Singapore" },
  SH: { ko: "세인트헬레나", en: "Saint Helena" },
  SI: { ko: "슬로베니아", en: "Slovenia" },
  SJ: { ko: "스발바르 얀마옌", en: "Svalbard and Jan Mayen" },
  SK: { ko: "슬로바키아", en: "Slovakia" },
  SL: { ko: "시에라리온", en: "Sierra Leone" },
  SM: { ko: "산마리노", en: "San Marino" },
  SN: { ko: "세네갈", en: "Senegal" },
  SO: { ko: "소말리아", en: "Somalia" },
  SR: { ko: "수리남", en: "Suriname" },
  SS: { ko: "남수단", en: "South Sudan" },
  ST: { ko: "상투메 프린시페", en: "São Tomé and Príncipe" },
  SV: { ko: "엘살바도르", en: "El Salvador" },
  SX: { ko: "신트마르턴", en: "Sint Maarten" },
  SY: { ko: "시리아", en: "Syria" },
  SZ: { ko: "에스와티니", en: "Eswatini" },
  TC: { ko: "터크스 케이커스 제도", en: "Turks and Caicos Islands" },
  TD: { ko: "차드", en: "Chad" },
  TF: { ko: "프랑스 남방·남극 지역", en: "French Southern Territories" },
  TG: { ko: "토고", en: "Togo" },
  TH: { ko: "태국", en: "Thailand" },
  TJ: { ko: "타지키스탄", en: "Tajikistan" },
  TK: { ko: "토켈라우", en: "Tokelau" },
  TL: { ko: "동티모르", en: "Timor-Leste" },
  TM: { ko: "투르크메니스탄", en: "Turkmenistan" },
  TN: { ko: "튀니지", en: "Tunisia" },
  TO: { ko: "통가", en: "Tonga" },
  TR: { ko: "튀르키예", en: "Türkiye" },
  TT: { ko: "트리니다드 토바고", en: "Trinidad and Tobago" },
  TV: { ko: "투발루", en: "Tuvalu" },
  TW: { ko: "대만", en: "Taiwan" },
  TZ: { ko: "탄자니아", en: "Tanzania" },
  UA: { ko: "우크라이나", en: "Ukraine" },
  UG: { ko: "우간다", en: "Uganda" },
  UM: { ko: "미국령 군소제도", en: "U.S. Minor Outlying Islands" },
  US: { ko: "미국", en: "United States" },
  UY: { ko: "우루과이", en: "Uruguay" },
  UZ: { ko: "우즈베키스탄", en: "Uzbekistan" },
  VA: { ko: "바티칸", en: "Vatican City" },
  VC: { ko: "세인트빈센트 그레나딘", en: "Saint Vincent and the Grenadines" },
  VE: { ko: "베네수엘라", en: "Venezuela" },
  VG: { ko: "영국령 버진아일랜드", en: "British Virgin Islands" },
  VI: { ko: "미국령 버진아일랜드", en: "U.S. Virgin Islands" },
  VN: { ko: "베트남", en: "Vietnam" },
  VU: { ko: "바누아투", en: "Vanuatu" },
  WF: { ko: "왈리스 푸투나", en: "Wallis and Futuna" },
  WS: { ko: "사모아", en: "Samoa" },
  XK: { ko: "코소보", en: "Kosovo" },
  YE: { ko: "예멘", en: "Yemen" },
  YT: { ko: "마요트", en: "Mayotte" },
  ZA: { ko: "남아프리카공화국", en: "South Africa" },
  ZM: { ko: "잠비아", en: "Zambia" },
  ZW: { ko: "짐바브웨", en: "Zimbabwe" },
};

export function countryName(
  code: string | null | undefined,
  locale: "ko" | "en" | string = "ko",
  fallback?: string | null,
): string {
  if (!code) return fallback ?? "—";
  const upper = code.toUpperCase();
  const entry = NAMES[upper];
  if (!entry) return fallback ?? upper;
  return locale === "en" ? entry.en : entry.ko;
}

/** @deprecated use countryName(code, locale, fallback) */
export function countryNameKo(code: string | null | undefined, fallback?: string | null): string {
  return countryName(code, "ko", fallback);
}
